name: gaia
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  logger: ^2.6.1
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.3
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
