name: Android PROD AAB (Artifacts only)

on:
  push:
    branches: [ main ]     # runs when PRs are merged to main
  workflow_dispatch:        # allow manual trigger if needed

jobs:
  build-prod:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Build prod AABs for both client flavors.
        # If you only want one, remove the other.
        client: [default, madani]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: stable
          cache: true

      - name: Pub get
        run: flutter pub get

      - name: Format (fail on diff)
        run: dart format --set-exit-if-changed .

      - name: Analyze (fail on warnings)
        run: dart analyze --fatal-infos

      - name: Codegen
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # 🔑 Recreate keystore + key.properties for the current client
      # Add the 8 repo secrets listed below
      - name: Prepare signing (per client)
        run: |
          mkdir -p android/app
          if [ "${{ matrix.client }}" = "default" ]; then
            echo "$ANDROID_KEYSTORE_BASE64_DEFAULT" | base64 -d > android/app/upload-keystore.jks
            cat > android/key.properties <<EOF
            storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD_DEFAULT }}
            keyPassword=${{ secrets.ANDROID_KEY_ALIAS_PASSWORD_DEFAULT }}
            keyAlias=${{ secrets.ANDROID_KEY_ALIAS_DEFAULT }}
            storeFile=upload-keystore.jks
            EOF
          else
            echo "$ANDROID_KEYSTORE_BASE64_MADANI" | base64 -d > android/app/upload-keystore.jks
            cat > android/key.properties <<EOF
            storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD_MADANI }}
            keyPassword=${{ secrets.ANDROID_KEY_ALIAS_PASSWORD_MADANI }}
            keyAlias=${{ secrets.ANDROID_KEY_ALIAS_MADANI }}
            storeFile=upload-keystore.jks
            EOF
          fi
        env:
          ANDROID_KEYSTORE_BASE64_DEFAULT: ${{ secrets.ANDROID_KEYSTORE_BASE64_DEFAULT }}
          ANDROID_KEYSTORE_BASE64_MADANI:  ${{ secrets.ANDROID_KEYSTORE_BASE64_MADANI }}

      # 🛠 Build signed PROD AAB (ENV=prod, flavor = <client>Prod)
      - name: Build PROD AAB (client=${{ matrix.client }})
        run: |
          flutter build appbundle \
            --flavor ${{ matrix.client }}Prod \
            -t lib/main.dart \
            --dart-define=CLIENT=${{ matrix.client }} \
            --dart-define=ENV=prod

      # ⬆️ Upload just the AAB as a downloadable artifact
      - name: Upload PROD AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.client }}-prod-aab
          path: build/app/outputs/bundle/**/app-*-release.aab
          if-no-files-found: error
