name: Android Dev Release (AAB + APK)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-dev:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        client: [default, madani]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: "17" }
      - uses: subosito/flutter-action@v2
        with: {channel: stable, cache: true }
      - run: flutter pub get
      - run: dart format .
      - run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build debug APK (client=${{ matrix.client }} Dev)
        run: |
          flutter build apk --debug \
            --flavor ${{ matrix.client }}Dev \
            -t lib/main.dart \
            --dart-define=CLIENT=${{ matrix.client }} \
            --dart-define=ENV=dev

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.client }}-dev-debug-apk
          path: build/app/outputs/flutter-apk/app-*-debug.apk
          if-no-files-found: error
